### ISSUE TITLE
I would like to include routes on this file

### ISSUE THREAD

**Issue by dhruv8433** [dhruv8433/contribution#1]
you have to add main 3 routes 

1. show users
2. insert user
3. delete user

using node and express js

**Comment by Varsani2520** [comment]
can i solve your issue

**Comment by dhruv8433** [comment]
sure go ahead

**Comment by Varsani2520** [comment]
![image](https://github.com/dhruv8433/contribution/assets/137641079/5936b6da-50db-47f4-b47a-1fac9370001a)
i completed this but i got...
